### ISSUE TITLE
Verilator required for builiding but not documented in the setup instructions

### ISSUE THREAD

**Issue by lolotobg** [ulx3s/blink#2]
Hi all, a proud owner of a new ULX3S here making his first steps.

Not sure whether the present issue has to do with the `blink` example specifically (expecting additional undocumented dependencies), or it's a more general omission from the prebuilt toolchain binaries (if `verialtor` is required in the common build flow).

Environment:
- Ubuntu 18.04 LTS
- The [KOTS toolchain](https://github.com/emard/ulx3s/blob/master/doc/MANUAL.md#precompiled-linux-opensource-tools-kost) installed via `dpkg` - version [ulx3s-toolchain_2020.10.12-2_amd64.deb](https://github.com/alpin3/ulx3s/releases/tag/v2020.10.12)
- The [precompiled tools](https://github.com/emard/ulx3s/blob/master/doc/MANUAL.md#precompiled-opensource-tools-for-all-platforms) installed from [fpga-toolchain-linux_x86_64-nightly-20201108.tar.gz](https://github.com/open-tool-forge/fpga-toolchain/releases/tag/nightly-20201108)

Trying to [build the blink code](https://github.com/ulx3s/blink#build-your-own-blink-led) results in the following error while attempting `make clean` (full output provided, but only the first line is unexpected):
```
bash: verilator: command not found
rm -rf ./obj_dir/   blinky/ blinky.bin 
rm -rf blinky.json ulx3s_out.config ulx3s.bit
```

The subsequent call to `make ulx3s.bit` results in:
```
bash: verilator: command not found
yosys blinky.ys 
yosys: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
Makefile:74: recipe for target 'blinky.json' failed
make: *** [blinky.json] Error 127
```

Those problems were resolved by a simple `sudo apt-get install verilator` - the blink code was sucessfully built and programmed.

**Comment by goran-mahovlic** [comment]
Thank you, added sudo apt-get install verilator to README
