### ISSUE TITLE
Running blinky on Windows requires make/WSL to installed.

### ISSUE THREAD

**Issue by mkvenkit** [ulx3s/blink#3]
Most Windows users will not have *make* installed. Also, looking at #2 it looks like Verilator needs to be installed as well, but as far as I understand, Verilator doesn't run directly on Windows. It requires WSL also. 

So a basic requirement of developing with ULX3S could be that WSL2 needs to be installed, and that should be clarified in the setup documentation, I think.

Update:

I was able to get everything working by installing WSL 2 first on Windows, installing Ubuntu, and then following your instructions for Linux setup. This might actually be the easier path than trying a native Windows setup.

**Comment by goran-mahovlic** [comment]
Thank you! Added bit info about WSL2
